### ISSUE TITLE
Check list for Diacritics

### ISSUE THREAD

**Issue by RosaWagner** [Etcetera-Type-Co/Epilogue#1]
This is to resume what we talked about during our meeting, so you have a roadmap ;) Have fun!
_I repeat, nothing here is a universal and static truth, these are conventions (some of them are debatable) that you chose to follow or not._

### Issues with Epilogue
- [X] Cedilla too large
- [X] Better to not slant dot, dieresis and ring at all
- [X] Macron too fat (in black master)
- [X] Comma accent below is too small (in black master)
- [x] Cedilla could go lower (thin master) 
- [x] Macron is too large (in thin master)
- [x] Dieresis too small
- [x] Comma accent is too big (in thin master)
- [x] Ogonek doesn't go low enough (thin master)
- [x] Accents not aligned horizontally
- [x] Accents not centred vertically
- [x] Accents above are too low
- [X] Accents below are too high
- [x] All small caps accentuated glyphs should be reviewed
- [x] All Vietnamese accents should be reviewed 
- [x] Accents are too slanted
- [x] Strokes, slash, bars and dot are not well positioned

### General advices
- **Horizontal alignment**: accents above and below of letters should be aligned in their center
- **Vertical alignment:** alignment of the accent with the letter is a matter of use and personal preference, but globally, the "gravity center" of the accent is more toward the basis than the actual center. 
- **Thickness and style** should be harmonious 
- **Dieresis** is supposed to be two dot accents, possibly narrower with an optically adjusted weight.
- **Caron.alt** for /L, /l, /t, /d : better if the top is aligned with ascender height, but /tcaron has its caron over the bar. It is not an apostrophe, it can look a bit like it but must differ from it, please refer to source below.
- **.narrow** can be used in Glyphs for /circumflex if needed above /idotless, as for /dieresis, /macron, /caron.
- **Catalan localized forms:** the/Ldot is used only before another/L: l•l L•L. The dot is supposed to be in the middle of the bounding box (if caps and ascenders have different height, you may find a compromise for the 2 versions to be aligned), in the middle of the 2 letters (same amount of space around the dot and previous and next letter).
- **Ogonek:** component is used for sharp letters /A /E /I /i /u but outlines are often decomposed with curved letters /O /U /o to link the ogonek to the curve. If the font is variable it might causes issues to go from black to thin with a linked ogonek, so a compromise can be found between with a sharp connexion but somehow in the continuity of the curve.
- **hbar, dcroat, Dcroat, Eth**: bar across stem is positioned about 3/4 inside letter, 1/4 outside (if not more, depends on design)
- **Sensitive forms:** for better proportions you can use case sensitive combining accents (.case), and therefore small caps accents (.sc) to build the small caps.
- **Vietnamese accents:** there are different ways to design and position them, I suggest to follow the advises in source link. 
- **Accents in italics (for dot, ring and dieresis):** it is of course not prohibited to slant the outline but it is often more harmonious to keep the upright outline and aligned them with the letter according to the slant axis. Sometimes the other accents don't need more adjustment as well.

### Sources
- [David Brezina article on ILT](https://ilovetypography.com/2009/01/24/on-diacritics/)
- [Diacritics Project](http://diacritics.typo.cz/index.php?id=1)
- [Vietnamese Accents](https://vietnamesetypography.com)
- [Contextual use of diacritics](https://www.setuptype.com/x/cod/), this is also good for spacing and kerning
- [Peter Bilak article about issues with caron](https://www.typotheque.com/articles/lcaron)
- [Glyphs tuto for Ldot](https://glyphsapp.com/tutorials/localize-your-font-catalan-punt-volat)

**Comment by sursly** [comment]
Perfect, thank you. I started in on a lot of these before you posted the issue, but my notes from our call were not as thorough as yours. I just pushed an update which I think fixes about half of what is here (and in other issues) but I'll keep plugging away.

**Comment by RosaWagner** [comment]
Don't hesitate to check the list and be precise in your commits description for better tracking (one commit per big task for example), and push several commits at the end of session.

**Comment by sursly** [comment]
Reworked all of this! Should be much improved.

**Comment by RosaWagner** [comment]
Few things I noticed:
- [ ] tilde in black is a bit fat compare to the other accents
- [ ] ogonek is okay in black but probably a bit too long in thin (i know, i would kill me too)
- [ ] position of ogonek in /U /e /o is still in between, you can move it a bit to the right I think
- [ ] look at the positioning of /macron when combined with dotaccent and dieresis; sometimes it is quite high

**Comment by sursly** [comment]
Checking about the tilde...by fat do you mean too wide or too heavy? Or both?

**Comment by RosaWagner** [comment]
too heavy mostly

**Comment by sursly** [comment]
OK great, latest commit should do the trick.

**Comment by RosaWagner** [comment]
- [ ] for the case sensitive Vietnamese comb accents to work you have to name them this way:
circumflexcomb_acutecomb.case, right it is circumflexacutecomb.case.
- [ ] I wonder if the size of the acute and grave combined with circumflex/breve is going to be a problem. 
- [ ] lowercase hookabove with circumflex is different from the other hookabove. (in black master with circumflex it looks also a bit too light). Maybe chose one of the two forms and keep it consistent everywhere? Your case hook above don't have a tail, so maybe the one with no tail for the lowercases too ? 
- [ ] Check aringacute.ss01 (mark positioning not consistent with base glyph) > Thin and Regular

Otherwise it look nicer and nicer ;)

**Comment by sursly** [comment]
Ok thanks for this!
I just pushed out an update that corrects these things, including the size of the acute/grave size with circumflex/breve comb.
