### ISSUE TITLE
Interpolation Issue - Regular - notequal.case

### ISSUE THREAD

**Issue by kenmcd** [Etcetera-Type-Co/Epilogue#20]
Interpolation Issue - Regular - notequal.case

File: Epilogue.glyphs (dated 2021-11-02, downloaded 2021-11-04)
Glyph name: notequal.case
Glyph number: 1018

There appears to be a different start point in the Black master.

![Interpolation Issue - Regular - notequal case 2021-11-05_11-50-12](https://user-images.githubusercontent.com/844920/140563803-686ee687-2184-4e2c-8fb9-ef74bb8ba431.gif)

**Comment by sursly** [comment]
Should be good now
