### ISSUE TITLE
Slant adjustment on Adobe Illustrator

### ISSUE THREAD

**Issue by fathurisi** [Etcetera-Type-Co/Epilogue#22]
Hi, I'm using Epilogue for a new brand visual identity. While making the visual identity guideline on Adobe Illustrator, I couldn't find slant adjustment on AI's variable font parameter, there's only the width editor. It will be beyond helpful if someone knows how to make slant adjustment possible on Adobe Illustrator.

![Screenshot 2022-02-08 172018](https://user-images.githubusercontent.com/99252673/152967841-3e2fa9b2-26fe-4cf2-a4d9-c24797be3489.jpg)

**Comment by kenmcd** [comment]
The slant axis is only available in an older version.
Download that version from here: 
https://github.com/Etcetera-Type-Co/Epilogue/tree/master/sources/legacy/2axesVF/

**Comment by sursly** [comment]
@fathurisi well @kenmcd is right. I'd love to bring back the slant axis, but had to separate things out for the current Google Fonts spec, unfortunately. However, it seems like Google might be moving toward re-incorporating that capability. I'm not sure.

**Comment by fathurisi** [comment]
Thanks @kenmcd and nice to know that @sursly. I'll be using it for a design organization so it's cool if they can have maximum feature.
