### ISSUE TITLE
Adding slant support to the variable font file

### ISSUE THREAD

**Issue by ayoolafelix** [Etcetera-Type-Co/Epilogue#23]
Hi, on the Epilogue website it's possible to adjust the slant but this doesn't work on downloading the font, only weight is available for adjustment.

**Comment by sursly** [comment]
Hi @ayoolafelix , yeah that's how the font used to be prior to integrating with Google Fonts. At the time, they weren't handling slant axis, so it was split up (removed) in favor of the separate Italic.

I'm working on adding it back in as a different version, but just haven't had time to finish. I'll update this issue when it is resolved.

**Comment by sursly** [comment]
In the meantime, if you'd like an OLDER version of the font, which has this capability (but not some of the other improvements of the recent version), I'm attaching it here.
[Epilogue[slnt,wght].ttf.zip](https://github.com/Etcetera-Type-Co/Epilogue/files/10262601/Epilogue.slnt.wght.ttf.zip)

**Comment by ayoolafelix** [comment]
Thank you very much!  I understand that these things take time. I'll be looking forward to it. There is also an issue with the '$' should i add it as a separate issue?

**Comment by ayoolafelix** [comment]
Thanks a bunch! I really appreciate it and all the other things you've put out.

**Comment by ayoolafelix** [comment]
Hi @sursly just checking in, I also wanted to bring to your notice that I created another issue for the dollar sign but I haven't gotten a response on it. Thank you

**Comment by sursly** [comment]
I just added the axis back to the variable file (and fixed the dollar sign)! I have no idea if this 2 axis variable file will be added to Google Fonts though. Any thoughts @RosaWagner

**Comment by RosaWagner** [comment]
If the font is onboarded with proper Italic, we won't updated with a slant axis that will remove direct access to the italic styles.
