### ISSUE TITLE
$ sign is not opticaly balanced

### ISSUE THREAD

**Issue by ayoolafelix** [Etcetera-Type-Co/Epilogue#24]
The dollar sign($) is not optically balanced with numbers.

**Comment by kenmcd** [comment]
And some of the other currency symbols appear to be a lighter weight than the figures.
For example:
![Currency-symbols-vs-figures](https://user-images.githubusercontent.com/844920/210627485-8b00557c-d172-42aa-8915-fb92212b0443.png)

**Comment by sursly** [comment]
Fixed this today!
