### ISSUE TITLE
Kerning "ďá"

### ISSUE THREAD

**Issue by qaywsxedcrfvtgb** [Etcetera-Type-Co/Epilogue#25]
<img width="262" alt="SCR-20230110-e1l" src="https://user-images.githubusercontent.com/9677765/211508450-954476b9-f980-4c3c-8172-d254235d7672.png">
Please make the kerning after "ď" better. Can't use it for the Czech language because of it.

**Comment by sursly** [comment]
Should be all set as of today's update.
