### ISSUE TITLE
Numbers appear as superscript

### ISSUE THREAD

**Issue by swanf** [Etcetera-Type-Co/Epilogue#26]
Fonts and numbers in the same sizes, the numbers appear as superscript. 

Both letters and numbers seen in this image are both 9.25pt same style

<img width="182" alt="Screen Shot 2023-06-09 at 8 45 05 AM" src="https://github.com/Etcetera-Type-Co/Epilogue/assets/136104660/2ace166d-7526-496a-b857-0c7bd33f5742">

**Comment by kenmcd** [comment]
Turn-off superscript in whatever application you are using.

**Comment by swanf** [comment]
@kenmcd Thanks for the reply. Superscript is not on which is the issue, sorry I missed that. Using InDesign and superscript is not toggled on.

**Comment by kenmcd** [comment]
Also check that the characters are not directly input using the Unicode code points for those characters.

**Comment by swanf** [comment]
@kenmcd 
Solved! It was not superscript. It was in paragraph styles; _Fractions_ in the Open Type had to be toggled off. I hope eventually fractions will be separated from superscript settings to avoid confusion. Such a great font. Thanks for the assist!

**Comment by swanf** [comment]
Summarizing for anyone with the same issue. 
If you have numbers appearing as superscript unexpectedly in a program such as InDesign. Toggle-off Fractions in the Open Type Options in your paragraph style.
