### ISSUE TITLE
Checklist for components

### ISSUE THREAD

**Issue by RosaWagner** [Etcetera-Type-Co/Epilogue#5]
_There is surely mistakes in my explanations. Any corrections are **very** welcome._

### Issues with Epilogue
- [x] Nested components
- [x] Mixed composites
- [x] Transformed components
- [x] Overlapping components
- [x] Anchors in composites
- [x] Missing virtual master in composites

### What is it ?
- **A composite** is a glyphs made of components.
- **A component** is a reference to a glyph within another glyph: so it contained outlines (with points coordinates and direction), but also other informations such as metrics, anchors and hinting. 
   
  - Logically, _a composite shouldn't contain anchors_, except for those already contained within the components — except exceptions as always.

- Glyphs app is making life easier for designers by hiding all the processing of components during the generation process. But, open source projects may be modified in other font editors which don't use the same process (and then the source file is messed up). In this context, it appears to be a good practice to master them yourself, before generation, and therefore offer to the world _cleaned_ outlines and controlled merging results — whatever format and process of generation chosen. 

### STATIC FONTS
- **Opentype fonts with a CFF compression (.otf files):** OTF-CFF fonts use PostScript hinting, which relies on PostScript curves (cubic curves which direction is counter-clockwise for the "shape" and clockwise fir the "counter-shape"). Composites should be decomposed (and usually merged) during generation, and PS hinting will be applied just as the reference glyph of the newly decomposed glyphs.

- **Opentype fonts with a TrueType (TT) compression (.ttf fonts):** composites should be kept if they are not mixed nor containing overlapping components. OTF-TTF fonts use TrueType hinting, which relies on TrueType curves (quadratic curves which direction is clockwise for the "shape" and counter-clockwise for the "counter-shape").

- **TT and PS hinting need _integer values_:** for the coordinates of points (on and off curve) and for the coordinates of the translation distance of the components. It is also recommended to not overlap hints (for more efficiency I guess, hinting is made to simplify shapes at small ppm sizes) — sometimes it makes sense though, depends on the design.

  - Any transformed components may cause (1) fractional coordinates if the composite is decomposed, (2) fractional translation distance if the glyph is not decomposed. In both cases, transformations as scaling, stretching, mirroring… may disturb the hinting which will try to round the coordinates and make errors while doing so. 

- **Filled or unfilled outline areas are deduced _by the rasterizer_:** (from what I understood, but really not sure about this). The font contains contours described by points coordinates, and it is assumed that outer and inner contours run in opposite direction, not overlapping. From these informations, the rasterizer fills the outlines.

  - Areas created by overlapping shapes (if merging is disable for export) can be interpreted as counter-shapes even if the contour direction is correct in the font editor (I think, not sure about this).

  - Overlapping shapes should be decomposed and merged during generation process, or before if you really want to have control over the points created and deleted during the merging. Indeed, since the conjunction of the 2 segments is not necessarily on the grid, you lose somehow control over the rounded coordinates of the created point. Then, since hinting is applied on on-curve points, it an be disturb if one of these points is deleted during merging. Overall, font editors and Fontmake are dealing quite well with all this, maybe just be careful when shapes are overlapping over an extremum point (which are the most important ones for hinting).

  - Mirroring a components is the same as applying a negative scale value (reversing the contour direction?). Any mirrored component should be decomposed before/during generation.
  
### VARIABLE FONTS / INTERPOLATION
- Variable fonts accept overlapping outlines and overlapping components, it is even recommended in some cases. So if you use one source to generate all formats, there is probably compromises to make in order to have good outlines for all kind of format.
- Bracket layer / virtual master : when you add a virtual master in a base-glyph, don’t forget to add it in all related composites. Components in bracket layers can cause problems during generation with Glyphs, better to use the parameter « decompose components in variable fonts » in font info. Or, according to your generation process, you may need to directly decompose the composites with bracket layers containing components. Fontmake doesn't decompose the composites with bracket layers, although generation should work if ALL the component have bracket layers at the same location in their respective base-glyph — even if one is not impacted by the virtual master (eg. if /a has bracket layers, /aacute also has to AND /acutecomb).
- It happened once that kerning was not exported to the glyph of the virtual master, so it is something to keep in mind when we will test the font.

### SOURCES
- [Typekit article explaining font compression](https://blog.typekit.com/2010/12/02/the-benefits-of-opentypecff-over-truetype/)
- [Glyphs tuto about bracket trick](https://glyphsapp.com/tutorials/alternating-glyph-shapes)
- [Glyphs issue about bracket trick](https://forum.glyphsapp.com/t/bracket-layer-not-working-in-glyphs-with-components-variable-font/13759)
- [Digital typefaces: description and format, Peter Karow](https://books.google.de/books?id=oomrCAAAQBAJ&pg=PA180&lpg=PA180&dq=contour+direction+bezier+rasterizer&source=bl&ots=XhflXu6MSS&sig=ACfU3U2MVQZ97rZNPfyovLLoybwTt4PMzw&hl=fr&sa=X&ved=2ahUKEwjew_DR-sfpAhVN-6QKHaKiD68Q6AEwAHoECAoQAQ#v=onepage&q&f=false)

**Comment by sursly** [comment]
I'll have to check back, but I think several of the issues might be resolved through fontmake (whether I've done that or not, tbd). But I've fixed the transformed components because I know even Google Fonts doesn't like that. I've un-nested many components, but surely not all. Again, might be decomposing things with fontmake (or possibly I could try glyphs as a custom parameter).

**Comment by sursly** [comment]
Hey can you look at the latest commit in regard to these issues 👆? I'm pretty sure we can check them all off.

**Comment by RosaWagner** [comment]
Fontmake doesn't seem to decompose and merge overlapping components in ttf static fonts (thinking about composites with cedilla, ogonek, slash, strokes).

**Comment by sursly** [comment]
Interestingly, in looking at Work Sans static TTFs the **Ơ** decomposes/merges fine but **ø** does not.

**Comment by sursly** [comment]
Yeah I'm in the Work Sans source, no merging there, and I don't see it in the build script either (yet).

**Comment by RosaWagner** [comment]
Here some answer for the bracket layers (there is no more in the font but it may help later):
https://github.com/googlefonts/fontmake/issues/670

**Comment by sursly** [comment]
Ah, so root components need the brace/bracket layer too? I was doing it for composites (that Ṃ you shared) without success, and stuck. I did see that @mekkablue just added a new glyph script to batch add these layers (**Insert Layers** - which would have been handy if I was keeping the brace method) https://github.com/mekkablue/Glyphs-Scripts/tree/master/Interpolation

**Comment by RosaWagner** [comment]
for next time ;)

**Comment by sursly** [comment]
OK, think I got all of the overlapping components (final outstanding issue above).

**Comment by mekkablue** [comment]
You need to recreate _Bracket_ layers (not brace layers) of a component in the composite. So if e has a bracket layer, eacute needs the same bracket layer. The script that helps you with that is Composite Variabler.

**Comment by sursly** [comment]
@mekkablue So, question: you don't need to recreate layers in components for brace layers?

**Comment by mekkablue** [comment]
No. You don’t.
