### ISSUE TITLE
Italic or slant axis

### ISSUE THREAD

**Issue by RosaWagner** [Etcetera-Type-Co/Epilogue#7]
@davelab6 or @m4rc1e can you help with this matter ?

Right now Epilogue has a Weight and Slant axis, therefore the axis should be defined as :
- wght [100-900]
- slnt [0- -12]
Correct ? Or were you saying something else during the kick off meeting ?

There are few glyphs (/a, /g, and related accentuated glyphs) to substitute in the slant axis.
Should we :
- set a boolean ital [0-1] "axis" (looks complicated for 2 substitutions… I guess everything happen in the STAT table and the designspace file, but I have no clue how to ~set this up, I looked into the recursive repo but there is a lot of scripts in there…~ make it work as in [recursive designspace file](https://github.com/arrowtype/recursive/blob/master/src/masters/sans/recursive_sans.designspace))
- bracket layers (that is what I would do)
- not do the substitutions and let the glyphs available in stylistic sets (easiest option)

**Comment by sursly** [comment]
Worth noting that I'm happy to swap the /a and /g with their more italic-friendly ss01 counterparts if it simplifies things. They're almost too flashy, now.

**Comment by RosaWagner** [comment]
It would definitely simplify things, but it is a important design decision. Whatever you choose we will make it work ;)

**Comment by RosaWagner** [comment]
Right now I am just confused between the different informations that I find and the discussion we had 2 weeks ago: 
- positive values for a Slant axis is against the spec but negative values are not intuitive. (Is it such an issue?)
- ital axis doesn't match your design right now: you have a slanted font, with a variation of the angle. 
- an "angle" custom axis could work, but it is not supported by CSS font-style property. (Is it such an issue?)
- GF doesn't serve slant axis yet, should we still prepare the font "as if" or have 2 variable fonts (upright and italic) with a weight axis each (and forget about the angle variation)? At least to have it on GF soon, maybe update it when there will be more browser support.

**Sources**
https://github.com/google/fonts/issues/2400
https://arrowtype.github.io/vf-slnt-test/slnt-ital-tests/index.html
https://github.com/arrowtype/recursive/tree/master/docs/03-slnt_ital-axis-rename-tests
https://docs.microsoft.com/ru-ru/typography/opentype/otspec182/dvaraxistag_slnt

**Comment by sursly** [comment]
My recollection from our first call – which is consistent with current GF – would be to have two variable fonts as you mention above, with only a weight axis. I've seen that explained in other threads as well. It isn't fun from a designer/developer perspective and/or as a font user. That said, it won't be hard to merge things back when there is a standard solution. But, we should figure it out soon since it will apply to five other families I'm working on for GF (Gluten slants forward and backward, so ITAL seems out of the question there).

**Comment by RosaWagner** [comment]
Okay, that sounds good to me, although it would be handy to modify the build script in order to generate 2 variable fonts from the same source (if it is possible, I haven't checked that out yet). But before doing so, Marc advised me to invoke directly @arrowtype to have an insightful opinion on this matter.

**Comment by sursly** [comment]
OK sounds good. It seems like moving it back to a slnt axis makes sense, and while negative values don't seem intuitive for the "italic", it would be consistent with what others are doing.

**Comment by RosaWagner** [comment]
I close this issue since we solved it by separating the 2 files
